// SIMA MHS feature modules - Tailwind CSS v4
(function(){
  const esc = v => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money = n => 'Rp' + Number(n||0).toLocaleString('id-ID');
  const date = v => v ? new Date(v).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}) : '-';
  const tag = (text, cls) => '<span class="inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold '+(cls||'bg-slate-100 text-slate-600')+'">'+esc(text)+'</span>';
  const empty = (title, body) => '<div class="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><div class="mx-auto mb-3 grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-700">∅</div><h3 class="font-bold text-slate-900">'+esc(title)+'</h3><p class="mt-1 text-sm text-slate-500">'+esc(body||'Belum ada data pada konteks ini.')+'</p></div>';
  const card = body => '<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">'+body+'</section>';
  const page = (title,sub,body) => '<div class="space-y-5"><div><h1 class="text-2xl font-extrabold tracking-tight text-slate-950">'+title+'</h1><p class="mt-1 text-sm text-slate-500">'+sub+'</p></div>'+body+'</div>';
  const table = (heads,rows) => '<div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr>'+heads.map(h=>'<th class="whitespace-nowrap px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">'+h+'</th>').join('')+'</tr></thead><tbody class="divide-y divide-slate-100">'+rows+'</tbody></table></div>';

  S.module = S.module || {};
  async function loadInbox(){ if(!sb)return; const {data,error}=await sb.from('dokumen').select('id,jenis,status,tahap_saat_ini,created_at,organisasi_id,proker:proker_id(id,nama,organisasi:organisasi_id(id,nama))').order('created_at',{ascending:false}); if(error){toast('Gagal memuat inbox: '+error.message);return;} S.module.inbox=data||[]; }
  async function loadStructure(){ if(!sb||!S.orgId){S.module.structure=[];return;} const {data,error}=await sb.from('keanggotaan').select('id,akun_id,jabatan,status,unit_id,profile:akun_id(id,nama,email,nim),unit:unit_id(id,nama)').eq('organisasi_id',S.orgId).order('jabatan'); if(error){toast('Gagal memuat struktur: '+error.message);return;} S.module.structure=data||[]; }
  async function loadGallery(){ if(!sb){S.module.gallery=[];return;} if(!S.orgId && ['wakil_rektor','bph'].includes(currentContext().kind)){ const {data,error}=await sb.from('foto_kegiatan').select('id,proker_id,drive_file_id,nama_file,urutan,created_at,proker:proker_id(id,nama)').order('created_at',{ascending:false}); if(error){toast('Gagal memuat galeri: '+error.message);return;} S.module.gallery=data||[];return;} const ids=(S.proker||[]).map(x=>x.id); if(!ids.length){S.module.gallery=[];return;} const {data,error}=await sb.from('foto_kegiatan').select('id,proker_id,drive_file_id,nama_file,urutan,created_at,proker:proker_id(id,nama)').in('proker_id',ids).order('created_at',{ascending:false}); if(error){toast('Gagal memuat galeri: '+error.message);return;} S.module.gallery=data||[]; }
  async function loadMeetings(){ if(!sb){S.module.meetings=[];return;} const ids=(S.proker||[]).map(x=>x.id); if(!ids.length){S.module.meetings=[];S.module.meetingDocs=[];return;} const {data:docs,error:de}=await sb.from('dokumen').select('id,proker_id,proker:proker_id(id,nama)').in('proker_id',ids); if(de){toast('Gagal memuat dokumen rapat: '+de.message);return;} const docIds=(docs||[]).map(x=>x.id); if(!docIds.length){S.module.meetings=[];S.module.meetingDocs=[];return;} const {data,error}=await sb.from('rapat').select('id,dokumen_id,nomor_rapat,tanggal,peserta,notulen,hasil,ditulis_oleh,created_at').in('dokumen_id',docIds).order('tanggal',{ascending:false}); if(error){toast('Gagal memuat rapat: '+error.message);return;} const map=Object.fromEntries((docs||[]).map(x=>[x.id,x])); S.module.meetings=(data||[]).map(x=>({...x,dokumen:map[x.dokumen_id]})); S.module.meetingDocs=docs||[]; }
  async function loadBudget(){ if(!sb){S.module.budget=[];return;} let q=sb.from('plafon_anggaran').select('id,organisasi_id,jumlah,organisasi:organisasi_id(id,nama,tipe,periode:periode_id(nama))'); if(S.orgId)q=q.eq('organisasi_id',S.orgId); const {data:plaf,error:pe}=await q.order('organisasi_id'); if(pe){toast('Gagal memuat plafon: '+pe.message);return;} const orgIds=(plaf||[]).map(x=>x.organisasi_id); if(!orgIds.length){S.module.budget=[];return;} const {data:pros}=await sb.from('proker').select('id,organisasi_id,item_anggaran(subtotal),pencairan_dana(jumlah)').in('organisasi_id',orgIds); const pids=(pros||[]).map(x=>x.id); const {data:real}=pids.length?await sb.from('realisasi').select('proker_id,jumlah').in('proker_id',pids):{data:[]}; S.module.budget=(plaf||[]).map(x=>{const ps=(pros||[]).filter(p=>p.organisasi_id===x.organisasi_id);const aj=ps.flatMap(p=>p.item_anggaran||[]).reduce((a,b)=>a+Number(b.subtotal||0),0);const cair=ps.flatMap(p=>p.pencairan_dana||[]).reduce((a,b)=>a+Number(b.jumlah||0),0);const re=(real||[]).filter(r=>ps.some(p=>p.id===r.proker_id)).reduce((a,b)=>a+Number(b.jumlah||0),0);return {org:x.organisasi,plafon:Number(x.jumlah||0),diajukan:aj,cair,realisasi:re,sisa:Number(x.jumlah||0)-aj};}); }
  async function loadCash(){ if(!sb){S.module.cash=[];return;} let ids=(S.proker||[]).map(x=>x.id); if(!ids.length && !S.orgId && ['wakil_rektor'].includes(currentContext().kind)){ const {data:all}=await sb.from('proker').select('id').order('tanggal_mulai'); ids=(all||[]).map(x=>x.id); } if(!ids.length){S.module.cash=[];return;} const {data,error}=await sb.from('pencairan_dana').select('id,proker_id,sumber_dana_id,jumlah,tanggal,tahap,proker:proker_id(id,nama),sumber_dana:sumber_dana_id(id,nama)').in('proker_id',ids).order('tanggal',{ascending:false}); if(error){toast('Gagal memuat pencairan: '+error.message);return;} S.module.cash=data||[]; }
  async function loadPeriods(){ if(!sb)return; const {data,error}=await sb.from('periode').select('id,nama,status,batas_lpj,created_at').order('created_at',{ascending:false}); if(error){toast('Gagal memuat periode: '+error.message);return;} S.module.periods=data||[]; }
  async function loadAudit(){ if(!sb)return; const {data,error}=await sb.from('jejak_audit').select('id,akun_id,sebagai,aksi,objek,objek_id,nilai_lama,nilai_baru,waktu,profile:akun_id(nama,email)').order('waktu',{ascending:false}).limit(100); if(error){toast('Gagal memuat audit: '+error.message);return;} S.module.audit=data||[]; }
  async function loadReports(){ if(!sb)return; let q=sb.from('dokumen').select('id,organisasi_id,status,tahap_saat_ini,created_at,catatan_pengaju,organisasi:organisasi_id(id,nama,tipe),proker:proker_id(id,nama)').eq('jenis','laporan_akhir').order('created_at',{ascending:false}); if(S.orgId)q=q.eq('organisasi_id',S.orgId); const {data,error}=await q; if(error){toast('Gagal memuat laporan: '+error.message);return;} S.module.reports=data||[]; }
  async function loadCalendar(){ S.module.calendar=(S.proker||[]).map(p=>({id:p.id,title:p.nama,start:p.mulai,end:p.selesai,status:p.status})).sort((a,b)=>String(a.start).localeCompare(String(b.start))); }
  async function loadReview(){ if(!sb||!S.dokId)return; const {data,error}=await sb.from('dokumen').select('id,jenis,status,tahap_saat_ini,created_at,organisasi_id,proker:proker_id(id,nama,organisasi_id,organisasi:organisasi_id(id,nama)),versi:dokumen_versi(id,nomor_versi,nama_file,ukuran_bytes,created_at)').eq('id',S.dokId).maybeSingle(); if(error){toast('Gagal memuat dokumen: '+error.message);return;} S.module.reviewDoc=data; }
  async function hydrate(v){const m={beranda:async()=>{await loadBudget();await loadInbox()},inbox:loadInbox,review:loadReview,struktur:loadStructure,galeri:loadGallery,rapat:loadMeetings,plafon:loadBudget,cair:loadCash,periode:loadPeriods,audit:loadAudit,laporan:loadReports,kalender:loadCalendar,dashboard:async()=>{await loadBudget();await loadInbox()}};if(m[v])await m[v]();}
  window.simaHydrate=hydrate;

  V.beranda=function(){const b=S.module.budget||[],i=S.module.inbox||[],p=S.proker||[];const aj=p.filter(x=>['proposal_diajukan','revisi'].includes(x.status)).length;const jalan=p.filter(x=>['berjalan','selesai'].includes(x.status)).length;const total=b.reduce((a,x)=>a+x.plafon,0),c=b.reduce((a,x)=>a+x.cair,0);return pageX('Beranda','Ringkasan aktivitas dan tugas pada semua konteks yang aktif.','<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-2xl border border-red-200 bg-red-50 p-5"><span class="text-xs text-red-700">Perlu review</span><b class="mt-1 block text-2xl text-red-900">'+i.length+'</b></div><div class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><span class="text-xs text-amber-700">Pengajuan aktif</span><b class="mt-1 block text-2xl text-amber-900">'+aj+'</b></div><div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><span class="text-xs text-emerald-700">Terlaksana/berjalan</span><b class="mt-1 block text-2xl text-emerald-900">'+jalan+'</b></div><div class="rounded-2xl bg-slate-950 p-5 text-white"><span class="text-xs text-slate-400">Dana cair</span><b class="mt-1 block text-2xl">'+money(c)+'</b></div></div><div class="mt-4 grid gap-4 lg:grid-cols-2"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h3 class="font-bold">Anggaran</h3><p class="text-sm text-slate-500">Plafon total konteks aktif</p></div><button class="text-sm font-semibold text-blue-700" data-go="plafon">Lihat →</button></div><p class="mt-4 text-2xl font-extrabold">'+money(total)+'</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><h3 class="font-bold">Kegiatan terbaru</h3><button class="text-sm font-semibold text-blue-700" data-go="proker">Semua proker →</button></div><div class="mt-2">'+(p.slice(0,5).map(x=>'<div class="flex items-center justify-between border-t border-slate-100 py-2"><span class="truncate pr-3">'+esc(x.nama)+'</span>'+tag(x.status||'-')+'</div>').join('')||'<p class="text-sm text-slate-500">Belum ada proker.</p>')+'</div></div></div>');};
Object.assign(V,{
    dashboard:function(){const b=S.module.budget||[],i=S.module.inbox||[];const total=b.reduce((a,x)=>a+x.plafon,0),aj=b.reduce((a,x)=>a+x.diajukan,0),c=b.reduce((a,x)=>a+x.cair,0);return pageX('Dashboard','Ringkasan kendali sesuai konteks aktif.','<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-2xl bg-slate-950 p-5 text-white"><span class="text-xs text-slate-400">Plafon</span><b class="mt-1 block text-2xl">'+money(total)+'</b></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><span class="text-xs text-slate-500">Diajukan</span><b class="mt-1 block text-2xl">'+money(aj)+'</b></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><span class="text-xs text-slate-500">Cair</span><b class="mt-1 block text-2xl">'+money(c)+'</b></div><div class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><span class="text-xs text-amber-700">Inbox</span><b class="mt-1 block text-2xl text-amber-900">'+i.length+'</b></div></div><div class="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><h3 class="font-bold">Perlu perhatian</h3><button class="text-sm font-semibold text-blue-700" data-go="inbox">Buka inbox →</button></div>'+(i.slice(0,5).map(x=>'<div class="flex items-center justify-between border-t border-slate-100 py-3"><div><b class="block">'+esc(x.proker?.nama||'Dokumen')+'</b><span class="text-xs text-slate-500">'+esc(x.tahap_saat_ini||'-')+' · '+date(x.created_at)+'</span></div>'+tag(x.status||'-','bg-amber-50 text-amber-700')+'</div>').join('')||'<p class="pt-3 text-sm text-slate-500">Tidak ada item.</p>')+'</div>');},
    inbox:function(){const rows=S.module.inbox||[];return pageX('Inbox review','Dokumen pada jalur review sesuai hak akses aktif.',rows.length?'<div class="space-y-3">'+rows.map(x=>'<article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h3 class="font-bold">'+esc(x.proker?.nama||'Dokumen')+'</h3><p class="text-sm text-slate-500">'+esc(x.proker?.organisasi?.nama||'-')+' · '+esc(x.jenis)+' · '+esc(x.tahap_saat_ini||'-')+'</p></div><div class="flex gap-2">'+tag(x.status||'-','bg-blue-50 text-blue-700')+'<button class="btn" data-review-doc="'+x.id+'">Buka review</button></div></div></article>').join('')+'</div>':empty('Inbox kosong'));},
    review:function(){const x=S.module.reviewDoc;if(!x)return pageX('Review dokumen','Pilih dokumen dari Inbox.',empty('Belum ada dokumen','Buka Inbox review lalu pilih dokumen.'));return pageX('Review dokumen',esc(x.proker?.nama||'Dokumen'),cardX('<div class="grid gap-3 md:grid-cols-4"><div><span class="text-xs text-slate-500">Organisasi</span><b class="block">'+esc(x.proker?.organisasi?.nama||'-')+'</b></div><div><span class="text-xs text-slate-500">Jenis</span><b class="block">'+esc(x.jenis)+'</b></div><div><span class="text-xs text-slate-500">Tahap</span><b class="block">'+esc(x.tahap_saat_ini)+'</b></div><div><span class="text-xs text-slate-500">Status</span><span class="mt-1 block">'+tag(x.status||'-','bg-blue-50 text-blue-700')+'</span></div></div><div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Versi dokumen: '+((x.versi||[]).length)+'</div><div class="mt-5 grid gap-3"><label>Komentar</label><textarea id="kk" rows="4" placeholder="Wajib untuk minta revisi"></textarea><p id="ke" class="text-xs text-red-600"></p><div class="flex flex-wrap gap-2"><button class="btn d" data-act="revisi">Minta revisi</button><button class="btn w" data-act="teruskan">Teruskan</button><button class="btn" data-act="setuju">Setujui</button></div></div>'));},
    struktur:function(){const rows=S.module.structure||[];return pageX('Struktur dan anggota','Susunan pengurus dan anggota organisasi.',cardX('<div class="flex items-center justify-between"><div><h3 class="font-bold">'+esc(currentContext().org||'Organisasi')+'</h3><p class="text-sm text-slate-500">Tambah anggota yang sudah memiliki akun SIMA.</p></div><div class="flex gap-2"><button class="btn" data-add-member>Buka form</button><label class="btn s cursor-pointer">Import CSV<input id="member-csv" type="file" accept=".csv,text/csv" class="hidden"></label></div></div><div id="member-form" class="hidden mt-4"><form id="member-add-form" class="grid gap-3 md:grid-cols-3"><input id="member-email" type="email" placeholder="Email akun"><select id="member-jabatan"><option>Anggota</option><option>Ketua</option><option>Wakil</option><option>Sekretaris</option><option>Bendahara</option><option>Presiden</option><option>Wakil Presiden</option><option>Menteri</option><option>Ketua Divisi</option></select><input id="member-unit" placeholder="ID unit opsional"><button class="btn md:col-span-3">Tambahkan</button><p id="member-error" class="text-xs text-red-600 md:col-span-3"></p></form></div>')+(rows.length?tableX(['Nama','NIM','Jabatan','Unit','Status'],rows.map(x=>'<tr><td class="px-4 py-3 font-semibold">'+esc(x.profile?.nama||'-')+'</td><td class="px-4 py-3">'+esc(x.profile?.nim||'-')+'</td><td class="px-4 py-3">'+tag(x.jabatan)+'</td><td class="px-4 py-3">'+esc(x.unit?.nama||'-')+'</td><td class="px-4 py-3">'+tag(x.status,x.status==='aktif'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600')+'</td></tr>').join('')):empty('Belum ada anggota')));},
    galeri:function(){const rows=S.module.gallery||[];return pageX('Galeri organisasi','Foto kegiatan tersimpan di Google Drive.',rows.length?'<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">'+rows.map(x=>'<a class="group rounded-2xl border border-slate-200 bg-white p-3 shadow-sm" href="https://drive.google.com/file/d/'+encodeURIComponent(x.drive_file_id||'')+'/view" target="_blank" rel="noreferrer"><div class="grid aspect-[4/3] place-items-center rounded-xl bg-slate-100 text-slate-400 text-3xl">▧</div><div class="pt-3"><b class="block truncate">'+esc(x.nama_file||'Foto kegiatan')+'</b><small class="text-slate-500">'+esc(x.proker?.nama||'-')+' · '+date(x.created_at)+'</small></div></a>').join('')+'</div>':empty('Galeri kosong','Foto akan muncul setelah LPJ diunggah.'));},
    rapat:function(){const rows=S.module.meetings||[],docs=S.module.meetingDocs||[];return pageX('Rapat','Catat rapat pengajuan dan keputusan rapat.',cardX('<form id="meeting-form" class="grid gap-3 md:grid-cols-2"><div><label>Dokumen</label><select id="meeting-doc">'+docs.map(x=>'<option value="'+x.id+'">'+esc(x.proker?.nama||'-')+'</option>').join('')+'</select></div><div><label>Nomor rapat</label><input id="meeting-number" type="number" min="1" value="1"></div><div><label>Tanggal</label><input id="meeting-date" type="date"></div><div><label>Hasil</label><select id="meeting-result"><option value="lanjut">Lanjut</option><option value="revisi">Revisi</option></select></div><div class="md:col-span-2"><label>Peserta</label><input id="meeting-participants" placeholder="Nama peserta"></div><div class="md:col-span-2"><label>Notulen</label><textarea id="meeting-notes" rows="5"></textarea></div><button class="btn md:col-span-2">Simpan rapat</button><p id="meeting-error" class="text-xs text-red-600 md:col-span-2"></p></form>')+(rows.length?tableX(['Proker','Rapat','Tanggal','Hasil','Notulen'],rows.map(x=>'<tr><td class="px-4 py-3 font-semibold">'+esc(x.dokumen?.proker?.nama||'-')+'</td><td class="px-4 py-3">#'+x.nomor_rapat+'</td><td class="px-4 py-3">'+date(x.tanggal)+'</td><td class="px-4 py-3">'+tag(x.hasil||'-')+'</td><td class="max-w-lg px-4 py-3 text-slate-600">'+esc(x.notulen||'-')+'</td></tr>').join('')):empty('Belum ada rapat')));},
    plafon:function(){const rows=S.module.budget||[];return pageX('Plafon dan anggaran','Plafon, pengajuan, cair, realisasi, dan sisa.',rows.length?'<div class="grid gap-4 lg:grid-cols-2">'+rows.map(x=>'<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h3 class="font-bold">'+esc(x.org?.nama||'-')+'</h3><p class="text-xs text-slate-500">'+esc(x.org?.tipe||'-')+'</p></div>'+tag(x.org?.periode?.nama||'-','bg-blue-50 text-blue-700')+'</div><div class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><span class="text-slate-500">Plafon</span><b class="block">'+money(x.plafon)+'</b></div><div><span class="text-slate-500">Diajukan</span><b class="block">'+money(x.diajukan)+'</b></div><div><span class="text-slate-500">Cair</span><b class="block">'+money(x.cair)+'</b></div><div><span class="text-slate-500">Realisasi</span><b class="block">'+money(x.realisasi)+'</b></div></div><div class="mt-4"><div class="mb-1 flex justify-between text-xs"><span class="text-slate-500">Sisa</span><b class="'+(x.sisa<0?'text-red-600':'text-emerald-700')+'">'+money(x.sisa)+'</b></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full '+(x.sisa<0?'bg-red-500':'bg-emerald-500')+'" style="width:'+Math.max(0,Math.min(100,x.plafon?(x.diajukan/x.plafon*100):0))+'%"></div></div></div></article>').join(''):empty('Belum ada plafon'));},
    cair:function(){const rows=S.module.cash||[];return pageX('Pencairan dan verifikasi','Catat dana cair sesuai hak Pembimbing/Wakil Rektor.',cardX('<form id="cash-form" class="grid gap-3 md:grid-cols-3"><select id="cash-proker">'+(S.proker||[]).map(p=>'<option value="'+p.id+'">'+esc(p.nama)+'</option>').join('')+'</select><select id="cash-source"><option>Memuat sumber dana...</option></select><input id="cash-amount" type="number" min="1" placeholder="Jumlah"><button class="btn md:col-span-3">Catat pencairan</button><p id="cash-error" class="text-xs text-red-600 md:col-span-3"></p></form>')+(rows.length?tableX(['Proker','Sumber','Tanggal','Tahap','Jumlah'],rows.map(x=>'<tr><td class="px-4 py-3 font-semibold">'+esc(x.proker?.nama||'-')+'</td><td class="px-4 py-3">'+esc(x.sumber_dana?.nama||'-')+'</td><td class="px-4 py-3">'+date(x.tanggal)+'</td><td class="px-4 py-3">#'+x.tahap+'</td><td class="px-4 py-3 font-semibold">'+money(x.jumlah)+'</td></tr>').join('')):empty('Belum ada pencairan')));},
    laporan:function(){const rows=S.module.reports||[];return pageX('Laporan akhir periode','Rekap seluruh proker pada periode aktif.',cardX('<form id="report-form" class="grid gap-3"><textarea id="report-note" rows="6" placeholder="Narasi laporan akhir periode"></textarea><button class="btn">Buat draft laporan</button><p id="report-error" class="text-xs text-red-600"></p></form>')+(rows.length?tableX(['Organisasi','Status','Tahap','Dibuat','Narasi'],rows.map(x=>'<tr><td class="px-4 py-3 font-semibold">'+esc(x.organisasi?.nama||'-')+'</td><td class="px-4 py-3">'+tag(x.status||'-')+'</td><td class="px-4 py-3">'+tag(x.tahap_saat_ini||'-','bg-blue-50 text-blue-700')+'</td><td class="px-4 py-3">'+date(x.created_at)+'</td><td class="max-w-xl px-4 py-3 text-slate-600">'+esc(x.catatan_pengaju||'-')+'</td></tr>').join('')):empty('Belum ada laporan akhir')));},
    periode:function(){const rows=S.module.periods||[];return pageX('Periode','Kelola periode aktif dan arsip.',cardX('<form id="period-form" class="grid gap-3 md:grid-cols-3"><input id="period-name" placeholder="2026/2027"><input id="period-lpj" type="date"><select id="period-status"><option value="aktif">Aktif</option><option value="ditutup">Ditutup</option></select><button class="btn md:col-span-3">Tambah periode</button><p id="period-error" class="text-xs text-red-600 md:col-span-3"></p></form>')+(rows.length?tableX(['Nama','Status','Batas LPJ','Dibuat','Aksi'],rows.map(x=>'<tr><td class="px-4 py-3 font-semibold">'+esc(x.nama)+'</td><td class="px-4 py-3">'+tag(x.status,x.status==='aktif'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600')+'</td><td class="px-4 py-3">'+date(x.batas_lpj)+'</td><td class="px-4 py-3">'+date(x.created_at)+'</td><td class="px-4 py-3">'+(x.status==='aktif'?'<button class="btn s" data-close-period="'+x.id+'">Tutup</button>':'<span class="text-xs text-slate-500">Arsip</span>')+'</td></tr>').join('')):empty('Belum ada periode')));},
    audit:function(){const rows=S.module.audit||[];return pageX('Jejak audit','Riwayat tindakan penting yang tercatat sistem.',rows.length?tableX(['Waktu','Aktor','Peran','Aksi','Objek'],rows.map(x=>'<tr><td class="px-4 py-3 whitespace-nowrap">'+date(x.waktu)+'</td><td class="px-4 py-3"><b>'+esc(x.profile?.nama||x.profile?.email||'-')+'</b></td><td class="px-4 py-3">'+esc(x.sebagai||'-')+'</td><td class="px-4 py-3">'+tag(x.aksi,'bg-blue-50 text-blue-700')+'</td><td class="px-4 py-3">'+esc(x.objek||'-')+'</td></tr>').join('')):empty('Belum ada jejak audit'));},
    kalender:function(){const rows=S.module.calendar||[];return pageX('Kalender kegiatan','Jadwal proker pada konteks aktif.',rows.length?'<div class="space-y-3">'+rows.map(x=>'<div class="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="w-20 shrink-0 rounded-xl bg-blue-50 p-3 text-center"><b class="block text-xl text-blue-700">'+(x.start?new Date(x.start).getDate():'-')+'</b><span class="text-xs text-slate-500">'+(x.start?new Date(x.start).toLocaleDateString('id-ID',{month:'short'}):'')+'</span></div><div><b>'+esc(x.title)+'</b><p class="mt-1 text-sm text-slate-500">'+date(x.start)+' – '+date(x.end)+' · '+tag(x.status||'-')+'</p></div></div>').join('')+'</div>':empty('Kalender kosong'));},
    profil:function(){const p=S.profile||{};return pageX('Profil saya','Identitas, foto, NIM, email, dan semua konteks akun.',cardX('<div class="grid gap-6 md:grid-cols-[140px_1fr]"><div class="text-center"><div class="mx-auto grid size-28 place-items-center overflow-hidden rounded-3xl bg-blue-50 text-3xl font-extrabold text-blue-700">'+(p.foto_url?'<img class="h-full w-full object-cover" src="'+esc(p.foto_url)+'" alt="">':esc((p.nama||'U').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()))+'</div><label class="mt-3 inline-block cursor-pointer text-sm font-semibold text-blue-700">Ganti foto<input id="profile-photo" type="file" class="hidden" accept="image/jpeg,image/png,image/webp"></label></div><form id="profile-form" class="grid gap-3"><div><label>Nama lengkap</label><input id="profile-nama" value="'+esc(p.nama||'')+'" required></div><div class="grid gap-3 sm:grid-cols-2"><div><label>NIM</label><input id="profile-nim" value="'+esc(p.nim||'')+'"></div><div><label>Email</label><input id="profile-email" type="email" value="'+esc(S.user?.email||p.email||'')+'"></div></div><div><span class="text-xs font-semibold text-slate-500">Status</span><div class="mt-1">'+tag(p.status||'-','bg-blue-50 text-blue-700')+'</div></div><p id="profile-error" class="text-xs text-red-600"></p><button class="btn">Simpan perubahan</button></form></div>')+cardX('<h3 class="font-bold">Peran & organisasi</h3><div class="mt-3 grid gap-3 sm:grid-cols-2">'+(S.ctxs||[]).map(x=>'<div class="rounded-xl border border-slate-200 p-3"><b class="block">'+esc(x.peran||'-')+'</b><span class="text-xs text-slate-500">'+esc(x.org||'-')+(x.periode?' · '+esc(x.periode):'')+'</span></div>').join('')+'</div>'));}
  });

  function pageX(t,s,b){return '<div class="space-y-5"><div><h1 class="text-2xl font-extrabold tracking-tight text-slate-950">'+t+'</h1><p class="mt-1 text-sm text-slate-500">'+s+'</p></div>'+b+'</div>';}
  function cardX(b){return '<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">'+b+'</section>';}
  function tableX(h,r){return '<div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr>'+h.map(x=>'<th class="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">'+x+'</th>').join('')+'</tr></thead><tbody class="divide-y divide-slate-100">'+r+'</tbody></table></div>';}

  MENU_MAP.organisasi[0][1]=[['beranda','Beranda'],['proker','Proker'],['undangan','Undangan kolaborasi'],['galeri','Galeri'],['laporan','Laporan akhir'],['struktur','Struktur dan anggota'],['profil','Profil saya']];
  MENU_MAP.bph[0][1]=[['beranda','Beranda'],['dashboard','Dashboard'],['proker','Semua proker'],['inbox','Inbox review'],['rapat','Rapat'],['galeri','Galeri pemantau'],['kalender','Kalender'],['plafon','Anggaran'],['struktur','Struktur BEM'],['profil','Profil saya']];
  MENU_MAP.pembimbing[0][1]=[['beranda','Beranda'],['dashboard','Dashboard organisasi'],['inbox','Inbox review'],['cair','Pencairan dan verifikasi'],['proker','Proker'],['galeri','Galeri'],['profil','Profil saya']];
  MENU_MAP.wakil_rektor[0][1]=[['beranda','Beranda'],['dashboard','Dashboard'],['plafon','Plafon'],['cair','Anggaran & pencairan'],['inbox','Inbox tahap BEM'],['proker','Semua proker'],['galeri','Galeri pemantau'],['audit','Jejak audit'],['profil','Profil saya']];
  MENU_MAP.staf_keuangan[0][1]=[['dashboard','Dashboard anggaran'],['plafon','Plafon'],['profil','Profil saya']];

  async function refresh(v){await hydrate(v);if(S.view===v)render();}
  document.addEventListener('click',async function(e){
    const g=e.target.closest('[data-go]');
    if(g&&V2[g.dataset.go])setTimeout(()=>refresh(g.dataset.go),0);
    const rv=e.target.closest('[data-review-doc]');
    if(rv){S.dokId=rv.dataset.reviewDoc;S.view='review';await refresh('review');}
    if(e.target.closest('[data-add-member]'))document.querySelector('#member-form')?.classList.toggle('hidden');
    const cp=e.target.closest('[data-close-period]');
    if(cp){if(!confirm('Tutup periode ini?'))return;const {error}=await sb.from('periode').update({status:'ditutup'}).eq('id',cp.dataset.closePeriod);if(error)toast(error.message);else{await loadPeriods();toast('Periode ditutup.');render();}}
  });
  document.addEventListener('submit',async function(e){
    if(e.target.id==='member-csv' && e.target.files?.[0]){
      const out=document.querySelector('#member-error');out.textContent='';
      const text=await e.target.files[0].text();
      const lines=text.split(/\\r?\\n/).filter(Boolean);
      if(lines.length<2){out.textContent='CSV kosong atau hanya header.';return;}
      const head=lines[0].split(',').map(x=>x.trim().toLowerCase());
      const ei=head.indexOf('email'),ji=head.indexOf('jabatan');
      if(ei<0){out.textContent='CSV wajib memiliki kolom email.';return;}
      let ok=0,fail=0;
      for(const line of lines.slice(1)){
        const cells=line.split(',').map(x=>x.trim());
        const email=cells[ei]; if(!email)continue;
        const jabatan=ji>=0&&cells[ji]?cells[ji]:'Anggota';
        const {data:p}=await sb.from('profiles').select('id,nama,status').eq('email',email).maybeSingle();
        if(!p||p.status!=='aktif'){fail++;continue;}
        const {error}=await sb.from('keanggotaan').insert({akun_id:p.id,organisasi_id:S.orgId,jabatan,status:'aktif',ditetapkan_oleh:S.user.id});
        if(error)fail++;else{ok++;await sb.from('notifikasi').insert({akun_id:p.id,organisasi_id:S.orgId,pesan:'Anda ditambahkan ke '+currentContext().org+' sebagai '+jabatan+'.'});}
      }
      await loadStructure();toast('Import anggota selesai: '+ok+' berhasil, '+fail+' dilewati.');render();
    }
    if(e.target.id==='member-add-form'){e.preventDefault();const err=document.querySelector('#member-error');err.textContent='';const email=document.querySelector('#member-email').value.trim(),jabatan=document.querySelector('#member-jabatan').value,unit=document.querySelector('#member-unit').value.trim()||null;const {data:p,error:pe}=await sb.from('profiles').select('id,nama,email,status').eq('email',email).maybeSingle();if(pe||!p){err.textContent=pe?.message||'Akun tidak ditemukan.';return;}if(p.status!=='aktif'){err.textContent='Akun belum aktif.';return;}const {error}=await sb.from('keanggotaan').insert({akun_id:p.id,organisasi_id:S.orgId,jabatan,status:'aktif',unit_id:unit,ditetapkan_oleh:S.user.id});if(error){err.textContent=error.message;return;}await sb.from('notifikasi').insert({akun_id:p.id,organisasi_id:S.orgId,pesan:'Anda ditambahkan ke '+currentContext().org+' sebagai '+jabatan+'.'});await loadStructure();toast('Anggota ditambahkan.');render();}
    if(e.target.id==='meeting-form'){e.preventDefault();const err=document.querySelector('#meeting-error');err.textContent='';const payload={dokumen_id:document.querySelector('#meeting-doc').value,nomor_rapat:Number(document.querySelector('#meeting-number').value||1),tanggal:document.querySelector('#meeting-date').value||null,peserta:document.querySelector('#meeting-participants').value.trim()||null,notulen:document.querySelector('#meeting-notes').value.trim()||null,hasil:document.querySelector('#meeting-result').value,ditulis_oleh:S.user.id};const {error}=await sb.from('rapat').insert(payload);if(error){err.textContent=error.message;return;}await loadMeetings();toast('Rapat disimpan.');render();}
    if(e.target.id==='cash-form'){e.preventDefault();const err=document.querySelector('#cash-error');err.textContent='';const amount=Number(document.querySelector('#cash-amount').value||0);const payload={proker_id:document.querySelector('#cash-proker').value,sumber_dana_id:document.querySelector('#cash-source').value,jumlah:amount};if(!payload.proker_id||!payload.sumber_dana_id||amount<=0){err.textContent='Lengkapi data pencairan.';return;}const {error}=await sb.from('pencairan_dana').insert(payload);if(error){err.textContent=error.message;return;}await loadCash();await loadBudget();toast('Pencairan dicatat.');render();}
    if(e.target.id==='report-form'){e.preventDefault();const err=document.querySelector('#report-error');err.textContent='';if(!S.orgId){err.textContent='Belum ada organisasi aktif.';return;}const note=document.querySelector('#report-note').value.trim();const {error}=await sb.from('dokumen').insert({organisasi_id:S.orgId,jenis:'laporan_akhir',status:'draft',tahap_saat_ini:'menteri',catatan_pengaju:note||null});if(error){err.textContent=error.message;return;}await loadReports();toast('Draft laporan akhir dibuat.');render();}
    if(e.target.id==='period-form'){e.preventDefault();const err=document.querySelector('#period-error');err.textContent='';const nama=document.querySelector('#period-name').value.trim(),batas=document.querySelector('#period-lpj').value||null,status=document.querySelector('#period-status').value;if(!nama){err.textContent='Nama periode wajib diisi.';return;}const {error}=await sb.from('periode').insert({nama,batas_lpj:batas,status});if(error){err.textContent=error.message;return;}await loadPeriods();toast('Periode ditambahkan.');render();}
  });
  async function sourceOptions(){const sel=document.querySelector('#cash-source');if(!sel||!sb)return;const {data,error}=await sb.from('sumber_dana').select('id,nama').order('nama');if(error){sel.innerHTML='<option>'+esc(error.message)+'</option>';return;}sel.innerHTML=(data||[]).map(x=>'<option value="'+x.id+'">'+esc(x.nama)+'</option>').join('')||'<option value="">Belum ada sumber dana</option>';}
  setInterval(()=>{if(S.view==='cair')sourceOptions();},1000);
})();
  if(sb){sb.auth.onAuthStateChange(function(event){if(event==='SIGNED_IN')setTimeout(function(){refresh('beranda');},0);});}

MENU_MAP.admin[0][1]=[['periode','Periode'],['akun','Akun dan penetapan'],['audit','Jejak audit'],['profil','Profil saya']];